apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-l4lw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-l4lw
    app.kubernetes.io/part-of: tkrw-pr712-0075-0043-app
  name: devfile-sample-l4lw
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-l4lw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-l4lw
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0043-tenant/tkrw-pr712-0075-0043-app/devfile-sample-l4lw@sha256:0baba403fc20b9dd8f6df388740d35fb4f0f9d9a056b488432ce924322c8decf
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
